### ISSUE TITLE
must clear compilation buffer when using "lein cljsbuild auto" on rebuilds

### ISSUE THREAD

**Issue by nahuel** [kototama/cljsbuild-mode#8]
If you use `"lein cljsbuild auto"` the compilation buffer is never erased when a new build starts, so all the errors/warning of previous builds are always present. This is annoying because they are here when you navigate the issues using `M-x next-error/previous-error`. The correct behaviour is to navigate (and see) only the errors/warnings of the latest build log, so the fix is to erase the compilation buffer when a new build starts.

**Comment by kototama** [comment]
True, that's not annoying. Are you still using it nonethless? I will try to fix it.

**Comment by kototama** [comment]
Fixed in master!
